import { categoryData } from "@/data/categoryData";
import Head from "next/head";
import { useStoreState } from "../../../store";
import { useQuery } from "react-query";

const JobCategory = () => {
  const { getCategories } = useStoreState();
  const { isLoading, data, isError, error } = useQuery("categories", () => {
    return getCategories();
  });

  return (
    <>
      <Head>
        <title>Rojgar-Job category</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="pt-8 px-12">
        <h1 className="text-3xl font-bold mb-4">Job Categories</h1>
        <ul className="grid grid-cols-2 gap-4 w-full">
          {isLoading ? (
            <h2>Loading...</h2>
          ) : isError ? (
            <h1> {error.message}</h1>
          ) : (
            <>
              {data.map((category, index) => (
                <li
                  key={category.id}
                  className="cursor-pointer  rounded-md px-4 py-2 bg-white shadow"
                >
                  <span>{category.name}</span>
                </li>
              ))}
            </>
          )}
        </ul>
      </div>
    </>
  );
};

export default JobCategory;
